version: '3.8'
services:
  ecommerce-matorresj-3:
    # build: ./
    image: matorresj/modulo_4_practica:latest
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: